# Generated by Django 4.2 on 2023-04-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
