# Generated by Django 4.2 on 2023-05-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuA', '0002_alter_menu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiracija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('inspiracijatitle', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=1000)),
                ('headerpicturepath', models.CharField(max_length=100)),
                ('contentpicturepath', models.CharField(max_length=100)),
                ('inspiracijaid', models.CharField(max_length=50)),
                ('contentid', models.CharField(max_length=50)),
                ('contenttitle', models.CharField(max_length=50)),
            ],
        ),
    ]
