# Generated by Django 4.2 on 2023-05-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuA', '0005_inspiracija_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiracija',
            name='clanak',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
