# Generated by Django 4.2 on 2023-04-16 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pictures')),
                ('date', models.DateField(auto_now_add=True)),
                ('serving', models.PositiveIntegerField()),
                ('preparation_time', models.PositiveIntegerField()),
                ('complexity', models.CharField(choices=[('JED', 'jednostavno'), ('SRE', 'srednje zahtjevno'), ('SLO', 'složeno')], default=1, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras', models.CharField(choices=[('ANT', 'antirecepti'), ('BGL', 'bez glutena'), ('KAL', 'bogato kalcijem'), ('VTC', 'bogati vitaminom C'), ('DIJ', 'dijetalna vlakna'), ('DJR', 'dječiji recepti'), ('MKL', 'malo kolesterola'), ('MMA', 'malo masnoće'), ('MSC', 'malo šećera'), ('MPD', 'mogu pripremati djeca'), ('NSK', 'niskokalorično'), ('PZZ', 'pogodno za zamrzavanje'), ('PDR', 'priprema dan ranije'), ('RNB', 'recepti naših baka'), ('RSP', 'recepti sa posvetom'), ('VEG', 'vegetarijanski')], default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePreparationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_method', models.CharField(choices=[('BTO', 'bez termičke obrade'), ('BLA', 'blanširanje'), ('KUH', 'kuhanje'), ('MAR', 'marininaje'), ('PEC', 'pečenje'), ('PKK', 'pečenje kolača i kruha'), ('PIR', 'pirjanje'), ('PRZ', 'przenje')], default=None, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('PR', 'proljeće'), ('LJ', 'ljeto'), ('ZI', 'zima'), ('CJ', 'cjelogodišnji')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars')),
                ('biography', models.TextField()),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourites', to='base.recipe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('HLA', 'hladna predjela'), ('TOP', 'topla predjela'), ('KIP', 'kruh i peciva'), ('JUH', 'juhe'), ('UDS', 'umaci, dipovi i salatni preljevi'), ('SAL', 'salate'), ('GLA', 'glavna jela'), ('PIV', 'prilozi i variva'), ('DES', 'deserti'), ('PIC', 'pića'), ('ZIM', 'zimnica')], default=None, max_length=3)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.userextended'),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to='base.recipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to='base.userextended')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=35)),
                ('qty', models.CharField(max_length=35)),
                ('unit', models.CharField(max_length=20)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.recipe')),
            ],
        ),
    ]
